/**
 * Minimal ZIP writer, replacing `jszip`.
 *
 * Why replace A working dependency
 *
 * `jszip` was 34.1% of the entire Worker bundle: 97,630 raw bytes and 28,444
 * gzipped, recorded in `perf-baseline.json` under `jszipShareOfBundlePercent`. It
 * was reachable from exactly one call site, `src/cores/wireguard.ts`, to build an
 * archive of two to a handful of small text files. Every deployment paid a third of
 * its bundle, and a third of its self-update payload, for that.
 *
 * The size budget is not a nicety here. The artifact is also the self-update payload
 * (`SOURCE_CONTENT`), and `npm run size` is a committed ratchet with a hard fail.
 * Reclaiming 28 KB of gzip from one dependency is worth more than any
 * micro-optimisation available anywhere else in the tree.
 *
 * Why stored rather than deflated
 *
 * This writer emits method 0 (stored, no compression). `jszip` emitted method 8
 * (deflate). Three reasons the change is right rather than merely convenient:
 *
 *   1. Implementing DEFLATE would reintroduce most of the bytes we just removed.
 *      Workers do expose `CompressionStream('deflate-raw')`, but wiring it in adds
 *      async plumbing and, for a 460-byte archive of highly-dissimilar short
 *      strings, saves on the order of a hundred bytes.
 *   2. Method 0 is the most universally supported entry type in the format. Every
 *      zip reader that exists handles stored entries; some minimal readers on
 *      embedded platforms handle *only* stored entries.
 *   3. The payload is a handful of WireGuard `.conf` files totalling a few hundred
 *      bytes. Compression ratio is irrelevant at that size; the file is downloaded
 *      once and imported.
 *
 * The visible consequence, stated because it is a real output change: archive bytes
 * differ from the previous implementation, so the `wireguard` and `amnezia` golden
 * fixtures record a different `byteLength`. That is a deliberate Class C change with
 * rewritten goldens, not a regression. The archive is still a valid ZIP, still has
 * the same entry names, and still contains byte-identical `.conf` contents, which
 * is what a client actually consumes.
 *
 * What this does not do
 *
 * No directories, no ZIP64, no encryption, no Unicode path flag, no multi-disk. The
 * inputs are ASCII filenames and small ASCII bodies, generated by this codebase, so
 * the supported subset is the subset that is reachable. Anything outside it should
 * fail loudly rather than be silently half-supported, so `zipStore` throws on a
 * filename that is not representable and on a total size that would need ZIP64.
 *
 * Format reference: PKWARE APPNOTE 6.3.x, sections 4.3.7 (local file header),
 * 4.3.12 (central directory header) and 4.3.16 (end of central directory).
 */

/** One file in the archive. */
export interface ZipEntry {
    /** Entry name. ASCII only; `/` is permitted but no entry may be a directory. */
    name: string;
    /** File body. */
    content: string;
}

/**
 * CRC-32 (IEEE 802.3, reflected, polynomial 0xEDB88320) as required by the ZIP
 * central directory.
 *
 * The table is built on first use rather than at module load: a request that never
 * exports an archive should not pay 1 KB of heap and 256 iterations for it. It is
 * then cached for the isolate's lifetime, so a deployment that exports often builds
 * it once.
 */
let crcTable: Uint32Array | null = null;

function crc32Table(): Uint32Array {
    if (crcTable) return crcTable;

    const table = new Uint32Array(256);
    for (let index = 0; index < 256; index += 1) {
        let value = index;
        for (let bit = 0; bit < 8; bit += 1) {
            value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
        }

        table[index] = value >>> 0;
    }

    crcTable = table;
    return table;
}

export function crc32(bytes: Uint8Array): number {
    const table = crc32Table();
    let crc = 0xffffffff;

    for (let index = 0; index < bytes.length; index += 1) {
        crc = table[(crc ^ bytes[index]) & 0xff] ^ (crc >>> 8);
    }

    return (crc ^ 0xffffffff) >>> 0;
}

/**
 * Little-endian writer over a fixed buffer.
 *
 * A fixed buffer rather than a growing array of chunks because the exact archive
 * size is computable in advance from the entry list, so one allocation is enough
 * and there is no concatenation pass.
 */
class ByteWriter {
    private readonly view: DataView;
    private readonly bytes: Uint8Array;
    private offset = 0;

    constructor(size: number) {
        const buffer = new ArrayBuffer(size);
        this.view = new DataView(buffer);
        this.bytes = new Uint8Array(buffer);
    }

    u16(value: number): void {
        this.view.setUint16(this.offset, value, true);
        this.offset += 2;
    }

    u32(value: number): void {
        this.view.setUint32(this.offset, value >>> 0, true);
        this.offset += 4;
    }

    raw(source: Uint8Array): void {
        this.bytes.set(source, this.offset);
        this.offset += source.length;
    }

    get position(): number {
        return this.offset;
    }

    /** The written buffer. Throws if the size prediction was wrong, which would
     *  otherwise produce a silently truncated or zero-padded archive. */
    finish(): Uint8Array {
        if (this.offset !== this.bytes.length) {
            throw new Error(`ZIP size mismatch: wrote ${this.offset} of ${this.bytes.length} bytes.`);
        }

        return this.bytes;
    }
}

const LOCAL_HEADER_SIZE = 30;
const CENTRAL_HEADER_SIZE = 46;
const END_RECORD_SIZE = 22;
const MAX_UINT32 = 0xffffffff;

/**
 * DOS date and time, as the format requires.
 *
 * A fixed 1980-01-01 00:00:00 stamp is emitted rather than the current time, for two
 * reasons that both matter more than an accurate timestamp on a generated file:
 * the archive becomes byte-reproducible, which is what lets a golden fixture assert
 * its length at all, and it stops the download from carrying the moment the
 * operator generated their config. 1980-01-01 is the format's zero point (year is
 * stored as an offset from 1980), so it is the natural "no information" value.
 */
const DOS_TIME = 0;
const DOS_DATE = 0x0021;

function encode(value: string): Uint8Array {
    return new TextEncoder().encode(value);
}

/**
 * Builds a ZIP archive with every entry stored uncompressed.
 *
 * Returns a `Uint8Array` the caller can hand straight to `new Response(...)`.
 */
export function zipStore(entries: readonly ZipEntry[]): Uint8Array {
    const prepared = entries.map(entry => {
        const name = encode(entry.name);
        const content = encode(entry.content);

        // A non-ASCII name would need the UTF-8 flag (bit 11) and a reader that
        // honours it. Nothing in this codebase generates one, so reject rather
        // than emit an entry whose name some readers would mangle.
        for (const byte of name) {
            if (byte > 0x7e || byte < 0x20) {
                throw new Error(`ZIP entry name must be printable ASCII: ${entry.name}`);
            }
        }

        return { name, content, crc: crc32(content) };
    });

    const localSize = prepared.reduce(
        (sum, entry) => sum + LOCAL_HEADER_SIZE + entry.name.length + entry.content.length,
        0
    );
    const centralSize = prepared.reduce((sum, entry) => sum + CENTRAL_HEADER_SIZE + entry.name.length, 0);
    const total = localSize + centralSize + END_RECORD_SIZE;

    // ZIP64 is the answer past 4 GiB. It is unreachable here (the inputs are a few
    // hundred bytes) and implementing it unused would be dead weight, so the limit
    // is asserted instead of handled.
    if (total > MAX_UINT32 || prepared.length > 0xffff) {
        throw new Error('Archive too large for ZIP32; ZIP64 is not supported.');
    }

    const writer = new ByteWriter(total);
    const offsets: number[] = [];

    for (const entry of prepared) {
        offsets.push(writer.position);

        writer.u32(0x04034b50); // local file header signature
        writer.u16(10); // version needed: 1.0, the floor for stored entries
        writer.u16(0); // general purpose flags: none
        writer.u16(0); // compression method: stored
        writer.u16(DOS_TIME);
        writer.u16(DOS_DATE);
        writer.u32(entry.crc);
        writer.u32(entry.content.length); // compressed size == uncompressed
        writer.u32(entry.content.length);
        writer.u16(entry.name.length);
        writer.u16(0); // extra field length
        writer.raw(entry.name);
        writer.raw(entry.content);
    }

    const centralStart = writer.position;

    for (let index = 0; index < prepared.length; index += 1) {
        const entry = prepared[index];

        writer.u32(0x02014b50); // central directory header signature
        writer.u16(0x031e); // version made by: 3.0, UNIX
        writer.u16(10); // version needed
        writer.u16(0); // flags
        writer.u16(0); // method: stored
        writer.u16(DOS_TIME);
        writer.u16(DOS_DATE);
        writer.u32(entry.crc);
        writer.u32(entry.content.length);
        writer.u32(entry.content.length);
        writer.u16(entry.name.length);
        writer.u16(0); // extra field length
        writer.u16(0); // comment length
        writer.u16(0); // disk number start
        writer.u16(0); // internal attributes
        // External attributes: UNIX mode 0644 in the high 16 bits. Without it some
        // extractors create the file with no permission bits at all.
        writer.u32(0o644 << 16);
        writer.u32(offsets[index]);
        writer.raw(entry.name);
    }

    writer.u32(0x06054b50); // end of central directory signature
    writer.u16(0); // this disk
    writer.u16(0); // disk with central directory
    writer.u16(prepared.length); // entries on this disk
    writer.u16(prepared.length); // entries total
    writer.u32(centralSize);
    writer.u32(centralStart);
    writer.u16(0); // comment length

    return writer.finish();
}
